name: "S3 Sync"
description: "Sync a directory to an AWS S3 repository"
author: jakejarvis
runs:
  using: docker
  image: docker://amazon/aws-cli:2.22.30
branding:
  icon: refresh-cw
  color: green
  